-- 1. Enable Row Level Security (RLS) is good practice, but for simplicity in this starter,
-- we will create tables that are public for authenticated users.

-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  username text,
  employee_id text unique, -- Changed: Employee ID must be unique as it is now the login identifier
  avatar_url text,
  updated_at timestamp with time zone,

  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
-- See https://supabase.com/docs/guides/auth/row-level-security for more details.
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Create a table for favorites
create table favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  news_id text not null,
  category text not null,
  title text not null,
  summary text,
  value_analysis text, -- Added: Missing field
  rating int,          -- Added: Missing field
  url text,
  source text,
  published_at text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Prevent duplicate favorites for the same news item by the same user
  unique(user_id, news_id)
);

alter table favorites enable row level security;

create policy "Users can view their own favorites." on favorites
  for select using (auth.uid() = user_id);

create policy "Users can insert their own favorites." on favorites
  for insert with check (auth.uid() = user_id);

create policy "Users can delete their own favorites." on favorites
  for delete using (auth.uid() = user_id);

-- Set up Storage for Avatars (Optional, skipping for now to keep it simple)
